### ISSUE TITLE
docker command does not pull amd64 image

### ISSUE THREAD

**Issue by nicoolaro** [atomicdata-dev/atomic-server#668]
when running docker run comand

`docker run -p 80:80 -p 443:443 -v atomic-storage:/atomic-storage joepmeneer/atomic-server

WARNING: The requested image's platform (linux/arm/v8) does not match the detected host platform (linux/amd64/v1) and no specific platform was requested
`

i am not sure how to find corrrect image for x86/64  , also i cannot find docker hub anywhere on the internet

**Comment by joepio** [comment]
You can try adding this flag:

`--platform linux/amd64`

**Comment by joepio** [comment]
Docker hub is here https://hub.docker.com/repository/docker/joepmeneer/atomic-server/general

**Comment by nicoolaro** [comment]
> You can try adding this flag:
> 
> `--platform linux/amd64`

tried, tag latest doesn't have amd64 image i will try earlier

**Comment by joepio** [comment]
Hmm indeed. It's fixed in the `develop` tag, though. Could you try that one?
![Uploading Screenshot 2023-10-02 at 10.12.02.png…]()

**Comment by nicoolaro** [comment]
@joepio  develop tag works , thanks!
