### ISSUE TITLE
please upgrade dependency on tantivy

### ISSUE THREAD

**Issue by jonassmedegaard** [atomicdata-dev/atomic-server#683]
Hi,

Tantivy has seen some recent upgrades, helping to generally modernize dependency crates (which simplifies getting this project included with Debian).

Please consider upgrading to tantivy v0.21.1

**Comment by jonassmedegaard** [comment]
...and while at it, upgrade base64 as well.

**Comment by joepio** [comment]
will do

**Comment by joepio** [comment]
Done!
