### ISSUE TITLE
please migrate to use kuchikiki

### ISSUE THREAD

**Issue by jonassmedegaard** [atomicdata-dev/atomic-server#684]
This project uses kuchiki which is stale. A new project, kuchikiki, has emerged and claims to be backwards compatible.

Please consider migrating from kuchiki to kuchikiki.

**Comment by joepio** [comment]
Probably a good idea!

**Comment by joepio** [comment]
Fixed in d54c8196399aa042ea4d1ac6168f97fa87e3f15b
