### ISSUE TITLE
Refreshing page on private resource shows "unauthorized resource"

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#686]
1. Open chrome / arc
1. Go to staging.atomicdata.dev
1. Create a new drive
1. Refresh
1. `Unauthorized resource`

<img width="552" alt="Screenshot 2023-11-02 at 15 16 12" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/da470aeb-b992-4170-9574-6af092a9d60c">

- This problem doesn't occur in `localhost`
- This problem doesn't occur in non-chromium browsers (firefox or safari)
- I suspect that the `store.setAgent` is called while the Resource is `loading`
- I saw that there was no Auth message in the `/ws` calls, which led to `unauthorized` resources

**Comment by joepio** [comment]
Fix didn't work

**Comment by joepio** [comment]
I noticed that there was no `AUTH` message in the `/ws` hooks

**Comment by joepio** [comment]
I just removed the `ga` cookies from `staging.atomicdata.dev` locally, and that also resolved the issue. 

We had that bug earlier, but I fixed it. This is really weird, because I specifically test for this in `irrelevant_cookie`, and the test passes.

I was also able to get an `unauthorized` error by logging in to `atomicdata.dev` and after that logging in to `staging.atomicdat.dev`. This resulted in two cookies, which seem to conflict... The thing is, we also have a fix and test for that!

```

    for enc in encoded_session_cookies {
        match get_auth_from_base64(&enc, requested_subject) {
            Ok(auth_vals) => return Ok(Some(auth_vals)),
            Err(e) => {
                if e.message.contains(WRONG_SUBJECT_ERR) && check_multiple {
                    // if the subject is wrong, we can try the next one
                    err = e;
                    continue;
                } else {
                    return Err(e);
                }
            }
        }
    }
```

**Comment by joepio** [comment]
I think the issue is resolved now... At least

**Comment by joepio** [comment]
It's still here in some cases..! The `e2e.spec` still has a failing test

**Comment by Polleps** [comment]
I've not had this issue for quite some time
