### ISSUE TITLE
For column "Select" search shows matches not only to the declared values, but all other, creating a lot of confusion

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#754]
For example, 'legal status' column has only two values:
![image](https://github.com/atomicdata-dev/atomic-data-docs/assets/21140376/cbfdd93d-467d-46cb-bb00-6e7b01d36fb4)
but when I try to find the proper value in the form, it shows me a lot of other stuff, which makes me completely lost:
![image](https://github.com/atomicdata-dev/atomic-data-docs/assets/21140376/e5d9951a-e765-46f6-948c-16ff43e410c8)

**Comment by Polleps** [comment]
Has been fixed
