### ISSUE TITLE
After renaming the class, in Relation column often only the old name stores

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#756]
the new name is "company"
![image](https://github.com/atomicdata-dev/atomic-data-docs/assets/21140376/fc0a9a12-ba89-4adf-9228-9c0276b5e479)
 though, only the old name "companies" is available as a resource type
![image](https://github.com/atomicdata-dev/atomic-data-docs/assets/21140376/1d5b9e9a-95a1-4927-a421-d61fa5eecc2c)

**Comment by turkhale** [comment]
Maybe, related to this - the name of the resource does not change.

https://github.com/atomicdata-dev/atomic-server/assets/21140376/2e48f451-dde1-4817-bd3d-1d3530c8fbcf

**Comment by turkhale** [comment]
Also, maybe related to this, or maybe a separate issue - when the new folder is created, it always contains an "Untitled-Folder-" bit, which is trashing of the namespaces. Just having "-Folder/<code>" is enough, for example:
http://localhost/app/edit?subject=http%3A%2F%2Flocalhost%2Fdrive%2**FIPLfs5Au**%2Ffolder%vxfejytcmeg

**Comment by joepio** [comment]
I think this may be setting the `name` instead of the `shortname`.

**Comment by joepio** [comment]
This is because a Table and a Class are related, but different. Renaming one does not rename the other. Syncing these is complex and leads to other edge cases (e.g. re-using the class).

Putting on wontfix, reopen if needed.
