### ISSUE TITLE
When class was not selected properly the first time later it does not allow to select it.

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#758]
[video](https://github.com/atomicdata-dev/atomic-data-docs/assets/21140376/ea1f9562-9c30-4f18-90d8-1dfbd87d5a87)

**Comment by Polleps** [comment]
This error is due to the SearchBox being a button. By default HTML forms submit when clicking any button (I hate html forms). We should make sure to always add `type='button'` except when we want it to submit.
