### ISSUE TITLE
Properties in the data atoms window ares not properly aligned.

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#762]
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/2f65cfcb-476f-4adf-a5f0-5c483bedc815)
Property values are not aligned in a column, which makes their readability poor. It should be like in Excel - two columns, one for properties, and another for values, with left-side alignment for each. I don't know what's best for properties with long names - truncate, extend, or else.

**Comment by joepio** [comment]
Similar to #761
