### ISSUE TITLE
The sequence of properties in card view does not match the one in the table view.

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#763]
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/c5c56943-3372-4aea-958d-0da8f6d6e4d8)
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/be65be97-d7bf-49e9-9850-6b7ded1dbedd)
Solution - when the user changes the column sequence in the table view, it should change the layout in the card view as well.

**Comment by joepio** [comment]
This is difficult, because the ordering is part of the `Table`, not from the `Class` or the `Resource` instance.

Perhaps we should make views customizable for these types of view, too.
