### ISSUE TITLE
Introduce the financial format for Number Column

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#764]
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/aa60befa-1062-487c-b3af-f325f74c8910)
Currently, only numbers and percentages are available, which makes financial documentation inconvenient. It should be available in a financial format like in Excel, with "," for separating thousands and "()" for negative numbers.

**Comment by joepio** [comment]
- Currency is stored on the Property
- We need a set of currencies + icons to refer to
- We need to customize formatting / styling everywhere numbers are used
- Use the [`Intl.numberformat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)

**Comment by turkhale** [comment]
I am talking more about having "," separators for thousands, millions, and billions, and parenthesis "()" formatting for negatives. Having currency is not very important, we show them anyway in the table.
