### ISSUE TITLE
Pop-up with a full column name when the name is truncated

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#765]
Some large forms contain long parameters, which are truncated. When hovering a mouse, the full name needs to be shown; otherwise, it is inconvenient to enter the data, as the user should remember what these parameters are or change the width of the column.
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/fc074f3b-c68b-4ca6-8564-c01860baa450)
It would be absolutely fantastic to have a class description in this pop-up, as some names of the classes will be abbreviated and not self-descriptive. The format is - the class' name in the first line and the description (or only a small portion of it) in the second line of the pop-up.

**Comment by joepio** [comment]
@Polleps consider using grid instead of flex. The `max-width: 8rem` needs to be removed.
