### ISSUE TITLE
The "delete drive" button should be available.

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#768]
Currently, I can remove all the resources in the drive, but I cannot delete it, which is strange - if I created the drive, I should be able to delete it altogether.

**Comment by joepio** [comment]
You can also delete the drive. Open the resource context menu in the bottom of the screen and pick the `delete` option.

<img width="515" alt="Screenshot 2024-01-08 at 13 23 59" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/ea98c6de-a70a-49f0-b07a-bb11530a2357">
