### ISSUE TITLE
Use `name` field by default in Ontology editor / Table editor

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#772]
- Search does not work properly when using custom `name-x` property

https://github.com/atomicdata-dev/atomic-server/assets/21140376/342df154-84aa-4973-a45f-20639aba31ba
But if I want to use class-specific names to distinguish, for example, country name or currency name, the lookup does not function.

**Comment by turkhale** [comment]
Perhaps we should always add the name property to all classes in the ontology editor / table editor by default?

That's a good idea!

**Comment by Polleps** [comment]
#1005 Should help with this.
