### ISSUE TITLE
Lookup window opens up and closes the class name, so the user needs to remember it instead of just looking.

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#773]
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/bfb95205-969a-4f86-8049-d6f536713764)
It must open down, not up.

**Comment by joepio** [comment]
The menu shows wherever there is room. It opens to the top if there is no room on the bottom.

Am I understanding correctly that this is the part that is the problem?
