### ISSUE TITLE
Potential GPL License violation

### ISSUE THREAD

**Issue by Property404** [atomicdata-dev/atomic-server#775]
I noticed `atomic_lib` is MIT-licensed, but has an optional dependency on `html2md`, which is GPL-licensed. `html2md` has multiple contributers who contributed their work under the GPL, so I don't think the fix is simple as "get permission from the original author to use a permissive license"

Since it's an optional dependency, I wonder if you could do something like only provide it under the MIT license if the `html` feature is not enabled? 

(I am not a lawyer)

CC: @Kaned1as

**Comment by joepio** [comment]
Thanks for bringing this to our attention! We'll look for an alternative :)

**Comment by joepio** [comment]
I reached out to @Kaned1as: https://gitlab.com/Kanedias/html2md/-/issues/11

**Comment by joepio** [comment]
The project will get a dual license and Atomic Server will be exempted!
