### ISSUE TITLE
Multiple resource parents are displayed

### ISSUE THREAD

**Issue by turkhale** [atomicdata-dev/atomic-server#776]
![image](https://github.com/atomicdata-dev/atomic-server/assets/21140376/64d2c102-89e1-472a-bad8-d70317c3ada2)
Multiple templates resources, with the same URL:
https://charm.terraphim.dev/app/data?subject=https%3A%2F%2Fcharm.terraphim.dev%2Ffolder%2FUntitled-Folder-fac3m3ekzuq%2Ftable%2FDRS-quantitative-scoring-template

**Comment by Polleps** [comment]
Should be fixed now
