### ISSUE TITLE
Add `search` option to CLI + atomic_lib

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#778]
@AlexMikhalev is interested in this

**Comment by AlexMikhalev** [comment]
To rephrase I need to be able to query from Rust using atomic_lib, cli is option and is an example of how to use API.

**Comment by joepio** [comment]
Alex does not necessarily need this feature at the moment.

**Comment by joepio** [comment]
@AlexMikhalev does need this feature now!

**Comment by joepio** [comment]
@AlexMikhalev The lib code for building a search URL is added to the latest development.

**Comment by joepio** [comment]
Also added the CLI search! Let me know if you run into issues :)
