### ISSUE TITLE
Atomic-lib get_resource doesn't pass agent in request to atomic server, forcing all resources to be public

### ISSUE THREAD

**Issue by AlexMikhalev** [atomicdata-dev/atomic-server#815]
Standard atomic lib sample:
```
    let test_article = "atomic-server/ontology/terraphim-ontology/class/article";
    let fetched_new_resource2 = store.get_resource(test_article).unwrap();
    println!("Fetched new resource: {:#?}", fetched_new_resource2);
```
only works for public resources because the agent isn't passed to get_resource even if it's set on the server. 
The fix is rather simple - use a passing agent like in crate::client::post_commit, but I am thinking may be worth creating another 
get_resource function and use the builder pattern to call like this store.get_resource(test_article).with(agent). To my understanding, there are performance implications for validating auth which is not needed for public resources.

References for builder pattern [1](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) [2](https://refactoring.guru/design-patterns/builder/rust/example)

**Comment by joepio** [comment]
Same as #787 perhaps?

**Comment by joepio** [comment]
Closing as duplicate, let me know if I misunderstood
