### ISSUE TITLE
Ugly select inputs in safari and firefox

### ISSUE THREAD

**Issue by Polleps** [atomicdata-dev/atomic-server#824]
**Safari**:
![image](https://github.com/atomicdata-dev/atomic-server/assets/8804875/964d67a1-d044-4971-89e2-5d24e93dc747)

**Firefox**:
<img width="295" alt="image" src="https://github.com/atomicdata-dev/atomic-server/assets/8804875/9fd42e5d-bed8-4697-9375-6e65919b4fcd">

**Chrome**:
<img width="371" alt="image" src="https://github.com/atomicdata-dev/atomic-server/assets/8804875/3fb10203-5a7d-45bf-9d20-fbe1741ecc39">

**Comment by Polleps** [comment]
Should be fixable by using `apperance: none` (also `background: none` for firefox) and adding a custom downwards pointing arrow to the end of the input

**Comment by joepio** [comment]
🤮
