### ISSUE TITLE
Make it easy to use the API from table view

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#855]
- User has table containing instances
- User wants to fetch the data... somewhere

How do we make their UX as easy as possible?

## Copy-Paste `/query` URL

- Add an action in the Table view for copying the whole `/query` URL, which should return current resources.

## Generate some JS / TS code blocks

- Using `@tomic/lib` stuff.

**Comment by Polleps** [comment]
We should make some 'how to fetch' type view where the user can choose a client lib (e.g. JS/TS, React, curl) and then generates it generates the code. Then we can make this available for more classes than just tables.

**Comment by joepio** [comment]
This view should also keep in mind what the class is, e.g. a "Table" needs a query, right?

In some cases we want users to utilize specific APIs, such as with collections or the `search` endpoint.
