### ISSUE TITLE
browser+test fails in CI

### ISSUE THREAD

**Issue by Polleps** [atomicdata-dev/atomic-server#880]
[https://github.com/atomicdata-dev/atomic-server/actions/runs/8893098009/job/24418585773?pr=879#step:6:407](https://github.com/atomicdata-dev/atomic-server/actions/runs/8893098009/job/24418585773?pr=879#step:6:407)

**Comment by joepio** [comment]
The thing that's odd here is that there are timeout errors, and that regular simple JS tests take almost 20 seconds.
