### ISSUE TITLE
Dead Link in the docs

### ISSUE THREAD

**Issue by StripedMonkey** [atomicdata-dev/atomic-server#883]
The link "[Linked Data](https://ontola.io/what-is-linked-data/)" is now leading to a 404. You can see the previous contents on the Internet Archive [here](https://web.archive.org/web/20211017155150/https://ontola.io/what-is-linked-data/)
The link is Located [here](https://github.com/atomicdata-dev/atomic-server/blob/0de422b74453cfb609f697141ad16edf97d790b0/docs/src/motivation.md?plain=1#L47)

**Comment by joepio** [comment]
Thanks! Fixed it.
