### ISSUE TITLE
z-index issues with resource selector

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#885]
When picking a resource, some items can overlap:

- The yamde editor has some too high elements
- The 'required' notice overlaps

<img width="627" alt="Screenshot 2024-05-26 at 15 40 43" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/956149ff-edf3-43a3-97ea-7152cc5ca34d">

## Solutions

IIRC there is this new CSS property that can be used, right @Polleps ?

**Comment by Polleps** [comment]
The yamde editor will be removed anyway so that's should not be an issue in the after the tip tap editor is done. As for the required notice, probably just a z-index thing, although they might be in different stacking contexts
