### ISSUE TITLE
Table not working if wrong drive is selected

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#893]
- Open a table from a different server, [like so](https://atomicdata.dev/app/show?subject=https%3A%2F%2Fstaging.atomicdata.dev%2Fdrive%2Fckggjb1d3md%2Ftable%2Ftest)

I'm assuming this goes wrong because the `/search` query is sent to the "current drive" instead of the drive shown in the resource.

How we can solve this:

## Always set current drive to opened resource

When opening a resource in a new drive, set that new drive as current one.

- When clicking some external thing (e.g. looking at the "description" property) this means you lose your "home" context. Could be a bit bothersome. Perhaps we should add a "back" button? Or open external things in a modal?

**Comment by Polleps** [comment]
Tables does not use the search endpoint. Its probably the collection that takes the serverURL from the store instead of the resource
