### ISSUE TITLE
Property edit dialog overflow issue

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#903]
<img width="740" alt="Screenshot 2024-06-25 at 11 51 23" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/c2bbc003-f74b-4991-8a85-10b74b8869d2">

**Comment by Polleps** [comment]
This is already fixed.

<img width="371" alt="image" src="https://github.com/atomicdata-dev/atomic-server/assets/8804875/d4dce0dd-fa4a-45f6-943f-26f3275cb447">
